#----------------------------------------------
# cubosemantico.py
# cubosemantico
# Alicia Gonzalez
# Ernesto Garcia
#----------------------------------------------

cubo_semantico = {
    "int": {
      "int": {
        "+":"int", 
        "-":"int", 
        "*":"int", 
        "/":"int", 
        ">":"bool", 
        ">=":"bool",
        "<=":"bool",
        "<":"bool", 
        "=":"int",
        "==": "bool", 
        "!=":"bool",
        "and":"Error", 
        "or":"Error",
        }, 
      "float": {
        "+":"float", 
        "-":"float", 
        "*":"float", 
        "/":"float", 
        ">":"bool", 
        ">=":"bool",
        "<=":"bool",
        "<":"bool", 
        "=":"int", 
        "==": "bool",
        "!=":"bool",
        "and":"Error", 
        "or":"Error",
        },  
      "string": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        }, 
      "bool": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },
      "Array": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },
      }, 
    "float":{
      "int": {
        "+":"float", 
        "-":"float", 
        "*":"float", 
        "/":"float", 
        ">":"bool", 
        ">=":"bool",
        "<=":"bool",
        "<":"bool", 
        "=":"float",
        "==": "bool", 
        "!=":"bool",
        "and":"Error", 
        "or":"Error",
        }, 
      "float": {
        "+":"float", 
        "-":"float", 
        "*":"float", 
        "/":"float", 
        ">":"bool", 
        ">=":"bool",
        "<=":"bool",
        "<":"bool", 
        "=":"float", 
        "==": "bool",
        "!=":"bool",
        "and":"Error", 
        "or":"Error",
        },  
      "string": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error",
        "==": "Error", 
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        }, 
      "bool": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error",
        "==": "Error", 
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },
      "Array": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },
      }, 
    "string":{
      "int": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        }, 
      "float": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },  
      "string": {
        "+":"string", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"string", 
        "==": "bool",
        "!=":"bool",
        "and":"Error", 
        "or":"Error",
        }, 
      "bool": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },
      "Array": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },
      }, 
    "bool":{
      "int": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        }, 
      "float": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        }, 
      "string": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==":"Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        }, 
      "bool": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"bool", 
        "==":"bool",
        "!=":"bool",
        "and":"bool", 
        "or":"bool",
        },
      "Array": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },
      },
    "List":{
      "int": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        }, 
      "float": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },  
      "string": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"bool",
        "<=":"bool",
        "<":"Error", 
        "=":"Error", 
        "==":"Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        }, 
      "bool": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==":"Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },
      "Array": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error",
        ">=":"Error",
        "<=":"Error", 
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },
      },
    "Array":{
      "int": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        }, 
      "float": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },  
      "string": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==":"Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        }, 
      "bool": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==":"Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },
      "Array": {
        "+":"Array", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },
      },
    }
test = cubo_semantico['int']['float']['+']
print test